sonar.projectKey=jzf407-rust
sonar.projectName=JZF407 Rust
sonar.sourceEncoding=UTF-8

sonar.sources=src,logic/src,build.rs
sonar.tests=logic/tests
sonar.rust.cargo.manifestPaths=Cargo.toml,logic/Cargo.toml
sonar.rust.clippy.enabled=false
sonar.rust.clippyReport.reportPaths=target/sonar/clippy-firmware.json,target/sonar/clippy-logic.json
sonar.rust.lcov.reportPaths=target/sonar/lcov.info

sonar.working.directory=target/sonar/.scannerwork
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
